/**
 * Open Legal Data API
 * With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website. https://openlegaldata.io/
 *
 * OpenAPI spec version: v1
 * Contact: hello@openlegaldata.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenLegalDataJavaScriptApi);
  }
}(this, function(expect, OpenLegalDataJavaScriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnnotationLabel', function() {
    it('should create an instance of AnnotationLabel', function() {
      // uncomment below and update the code to test AnnotationLabel
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be.a(OpenLegalDataJavaScriptApi.AnnotationLabel);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property trusted (base name: "trusted")', function() {
      // uncomment below and update the code to test the property trusted
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property _private (base name: "private")', function() {
      // uncomment below and update the code to test the property _private
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property manyAnnotationsPerLabel (base name: "many_annotations_per_label")', function() {
      // uncomment below and update the code to test the property manyAnnotationsPerLabel
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property useMarker (base name: "use_marker")', function() {
      // uncomment below and update the code to test the property useMarker
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property annotationValueType (base name: "annotation_value_type")', function() {
      // uncomment below and update the code to test the property annotationValueType
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new OpenLegalDataJavaScriptApi.AnnotationLabel();
      //expect(instance).to.be();
    });

  });

}));
