/**
 * Open Legal Data API
 * With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website. https://openlegaldata.io/
 *
 * OpenAPI spec version: v1
 * Contact: hello@openlegaldata.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenLegalDataJavaScriptApi);
  }
}(this, function(expect, OpenLegalDataJavaScriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenLegalDataJavaScriptApi.CaseAnnotationsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CaseAnnotationsApi', function() {
    describe('caseAnnotationsCreate', function() {
      it('should call caseAnnotationsCreate successfully', function(done) {
        //uncomment below and update the code to test caseAnnotationsCreate
        //instance.caseAnnotationsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('caseAnnotationsDelete', function() {
      it('should call caseAnnotationsDelete successfully', function(done) {
        //uncomment below and update the code to test caseAnnotationsDelete
        //instance.caseAnnotationsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('caseAnnotationsList', function() {
      it('should call caseAnnotationsList successfully', function(done) {
        //uncomment below and update the code to test caseAnnotationsList
        //instance.caseAnnotationsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('caseAnnotationsPartialUpdate', function() {
      it('should call caseAnnotationsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test caseAnnotationsPartialUpdate
        //instance.caseAnnotationsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('caseAnnotationsRead', function() {
      it('should call caseAnnotationsRead successfully', function(done) {
        //uncomment below and update the code to test caseAnnotationsRead
        //instance.caseAnnotationsRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('caseAnnotationsUpdate', function() {
      it('should call caseAnnotationsUpdate successfully', function(done) {
        //uncomment below and update the code to test caseAnnotationsUpdate
        //instance.caseAnnotationsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
